### PR TITLE
Convert Windows stubs to Unicode

### LINKED ISSUE #57: Windows: Unicode characters in the program name/path makes spawn fail
According to [its documentation](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa), `CreateProcess` defaults to the ASCII if `UNICODE` is not defined.

I'm not able to find this macro defined anywhere in spawn and in any case, `v_prog` is passed as-is to `CreateProcess` which means the string is not UTF-16 encoded.

If you call `spawn` on Windows with `~prog:"C:\path\to\a\Unicěde.exe"` the process will fail with:
```
Error: CreateProcess(): No such file or directory
```

### PR DESCRIPTION
**Pull request by dra27**
Subsumes #55. Fixes #57. Fixes https://github.com/ocaml/dune/issues/10180 which then fixes https://github.com/ocaml/opam/issues/5861.

Windows OCaml uses UTF-8 internally for environment variables. The `spawn_windows` stub was using the ANSI version of `CreateProcess` (`CreateProcessA`) which causes the environment to become corrupted if the environment contained any non-ASCII characters (i.e. any UTF-8 sequences).

Support for Windows 98 ended in July 2006, so I think we can risk using the Unicode version of `CreateProcess` 😉 The code mirrors that for `Unix.create_process`.

### CODE REVIEW

File: src/dune [hunk 1]
```diff
@@ -3,11 +3,20 @@
...
  ;; c_library_flags. However, this would require testing that it is
  ;; supported.
  (libraries unix threads))
+
+(rule
+  (with-stdout-to flags.sexp
+    (run ocaml %{dep:flags.ml})))
+
+(rule
+  (with-stdout-to flags.ml
```
Comment (emillon) [inline src/dune:21]: I think that this might add the `Flags` module to the library.

File: src/spawn_stubs.c [hunk 2]
```diff
@@ -1,5 +1,25 @@
 #define _GNU_SOURCE
 
+/* Must come before any other caml/ headers are included */
+#define CAML_INTERNALS
+
+#ifdef _WIN32
```
Comment (kit-ty-kate) [inline src/spawn_stubs.c:6]: Instead of changing the `dune` file:
```suggestion
#ifdef _WIN32

#define UNICODE
#define _UNICODE

```
Based on a comment by @emillon in https://github.com/ocaml/dune/pull/10212#issuecomment-1980368796

File: src/dune (hunk 1 above)
Comment (dra27) [reply src/dune]: Gah, yes indeed! Fix pushed for the original approach, but actually `enabled_if` is arguably "better", given that it's then a semi-pure Dune solution.

File: src/spawn_stubs.c (hunk 2 above)
Comment (dra27) [reply src/spawn_stubs.c:6]: My only concern is that `UNICODE` and `_UNICODE` must either be defined everywhere or nowhere (OCaml headers can pull in `windows.h` or parts of it as well, ending up with a similar problem to that which we have already had with `CAML_INTERNALS`).

The other benefit of putting it in flags is that any additional C files correctly inherit it, but that's really never likely to apply here. Given that we already have the `_GNU_SOURCE` definition (which is where it should go - i.e. right at the top).

I don't mind, though - how strong opinions against doing it "philosophically" correctly, if more complicatedly, in the `dune` file?

**Comment by rgrinberg** [comment]
@nojb could you have a look?

File: src/spawn.ml [hunk 3]
```diff
@@ -42,13 +42,16 @@ module Env_win32 : Env = struct
...
-    let len = List.fold_left env ~init:1 ~f:(fun acc s -> acc + String.length s + 1) in
-    let buf = Buffer.create len in
-    List.iter env ~f:(fun s ->
-      Buffer.add_string buf s;
-      Buffer.add_char buf '\000');
-    Buffer.add_char buf '\000';
-    Buffer.contents buf
+    if env = [] then
+      "\000\000"
+    else
```
Comment (nojb) [inline src/spawn.ml:47]: Can you say a word about this change?

File: src/spawn_stubs.c (hunk 2 above)
Comment (nojb) [reply src/spawn_stubs.c:6]: I agree it is better to do it in the `dune` file.

File: src/spawn_stubs.c [hunk 4]
```diff
@@ -648,22 +679,22 @@ CAMLprim value spawn_windows(value v_env,
   if (!dup2_and_clear_close_on_exec(v_stdin , &si.hStdInput ) ||
       !dup2_and_clear_close_on_exec(v_stdout, &si.hStdOutput) ||
       !dup2_and_clear_close_on_exec(v_stderr, &si.hStdError )) {
-    win32_maperr(GetLastError());
+    caml_win32_maperr(GetLastError());
     close_std_handles(&si);
     uerror("DuplicateHandle", Nothing);
```
Comment (nojb) [inline src/spawn_stubs.c:684]: If we error out here, we will leak the strings allocated above. Maybe invert the order?

**Review by nojb — APPROVED** [review]
LGTM (modulo the tweaks below)

**Comment by emillon** [comment]
ok, thanks. my only concern with the dune file was that it requires changing a bit our bootstrap system in dune but that's fine with me.

File: src/spawn.ml (hunk 3 above)
Comment (dra27) [reply src/spawn.ml:47]: The environment block is supposed to be terminated with two NUL characters - if there are any bindings, that obviously in the other branch (and did in the ANSI version too). When there are no bindings, the ANSI version was passing a pointer to the _OCaml_ string `"\000"` but that will have had an additional NUL terminator so it quietly worked. With the wide version, the issue was instantly revealed by one of the tests where `CreateProcessW` will have received two NUL _bytes_ (i.e. a NUL wchar_t) but will have then "segfaulted" reading past the end of that buffer (`CreateProcessW` actually translated that to an invalid argument, which worryingly suggests that it carried on reading random memory and instead got upset that there was no `=` character anywhere or some such😱)

I'm not sure if it's worth a comment in the code - `CreateProcess` does indicate that the block should be a series of nul-terminated strings themselves terminated by another nul, it's just hazy on the case of an empty environment (not surprisingly, really).

File: src/spawn_stubs.c (hunk 4 above)
Comment (dra27) [reply src/spawn_stubs.c:684]: Oh blimey, good catch. (Another) revised version incoming...

File: src/spawn.ml (hunk 3 above)
Comment (nojb) [reply src/spawn.ml:47]: Thanks for the explanation; but then isn't it wrong in the compiler?

https://github.com/ocaml/ocaml/blob/dfb7abefb4df82804703e6609d957f3dcda64d29/otherlibs/unix/unix_win32.ml#L999-L1003

Comment (dra27) [reply src/spawn.ml:47]: Yeah, I had that same shock thought! 🙂 Just awaiting a train, and then I’ll flex some environments…

Comment (dra27) [reply src/spawn.ml:57]: OK, OCaml's fine because `createprocess.c` speculatively adds a nul character. I was speculatively adding that character but not zeroing it. I've fixed it by not adding it, as I think it's nicer that the function in spawn.ml is entirely responsible for producing the UTF-8 version and then the C stub transcodes exactly that string.

File: src/spawn_stubs.c (hunk 4 above)
Comment (dra27) [reply src/spawn_stubs.c]: Done!

**Comment by dra27** [comment]
While looking at it again, for some reason the check for nul characters in environment values was only being done in `Env_unix` so I shifted the function out of there and used it in `Env_win32` as well.

Hopefully this is the last version 🙂

**Review by nojb — APPROVED** [review]
LGTM (after the latest changes). Thanks!
